---
abstract: 'Useful set for work with HTTP'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  Test::More: 0
  URI: 0
  lib::abs: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Easy
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  Scalar::Util: 0
  Time::Local: 0
version: 0.03
